openapi: 3.1.0
info:
  title: summary
  description: summary
  version: 1.0.0
servers:
  - url: http://localhost:10100
    description: 本机测试

paths:
  /API/Login:
    get:
      summary: 登陆

      parameters:
        - in: query
          name: username
          required: true
          description: 用户名
          schema:
            type: string
        - in: query
          name: password
          required: true
          description: 密码
          schema:
            type: string

      responses:
        '400':
          description: 登陆失败
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 登陆失败的具体信息

        '200':
          description: 返回一个json，包含用户名和token
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                  properties:
                    msg:
                      type: string
                      description: 登陆信息
                    username:
                      type: string
                      description: 用户名
                    token:
                      type: string
                      description: 登陆token

  /API/Register:
    get:
      summary: 注册user权限账户的API

      parameters:
        - in: query
          name: username
          required: true
          description: 用户名
          schema:
            type: string
        - in: query
          name: password
          required: true
          description: 密码
          schema:
            type: string
        - in: query
          name: email
          required: true
          description: 邮箱
          schema:
            type: string

      responses:
        '200':
          description: 返回一个json, 包含注册信息
          content:
            application/json:
              schema:
                type: string
                items:
                  type: object
                  properties:
                    msg:
                      type: string
                      description: 注册信息
                    username:
                      type: string
                      description: 用户名
        '400':
          description: 因参数有误导致的注册失败
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 注册失败的具体信息
        '500':
          description: 因服务器内部错误导致的注册失败
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 注册失败的具体信息
                  error:
                    type: string
                    description: 服务器内部错误信息

  /API/user/UserUpdateSelf:
    get:
      description: 能更改user权限用户自身信息的API(未完成)

      parameters:
        - name: username
          in: query
          description: 用户名
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: 密码
          required: true
          schema:
            type: string
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功更改用户自身信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                    description: 用户名

  /API/admin/CreateUser:
    get:
      summary: 创建用户
      description: admin权限下任意创建用户的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数
          required: true
        - name: password
          in: query
          schema:
            type: string
            description: 必须在URL里提供的密码参数
          required: true
        - name: email
          in: query
          schema:
            type: string
            description: 必须在URL里提供的邮箱参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功创建用户
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 用户名已存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

        '500':
          description: 密码加密失败或用户创建错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/UpdateUser:
    get:
      summary: 更新用户信息
      description: admin权限下任意更新用户信息的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数，用于查询用户
          required: true
        - name: password
          in: query
          schema:
            type: string
            description: 可选，更改密码
          required: false
        - name: email
          in: query
          schema:
            type: string
            description: 可选，更改邮箱
          required: false
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功更新用户信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 用户名不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息
        '500':
          description: 密码加密失败或用户更新错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/UserDelete:
    get:
      summary: 删除用户
      description: admin权限下任意删除用户的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功删除用户
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 用户名不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息
        '500':
          description: 用户删除错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/UserGetByName:
    get:
      summary: 查询用户信息
      description: admin权限下根据用户名任意查询用户信息的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功获取用户信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 用户名不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/GetAdminByName:
    get:
      summary: 查询管理员信息
      description: admin权限下根据管理员名任意查询管理员信息的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功获取管理员信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 管理员不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/CreateAdmin:
    get:
      summary: 创建管理员
      description: admin权限下任意创建管理员的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的用户名参数
          required: true
        - name: password
          in: query
          schema:
            type: string
            description: 必须在URL里提供的密码参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功创建管理员
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '500':
          description: 密码加密失败或管理员创建错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/DeleteAdminByName:
    get:
      summary: 删除管理员
      description: admin权限下任意删除管理员的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须在URL里提供的管理员账号名参数
          required: true
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功删除管理员
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '400':
          description: 管理员不存在或删除错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

  /API/admin/UpdateAdmin:
    get:
      summary: 更新管理员信息
      description: admin权限下任意更新管理员信息的API
      parameters:
        - name: username
          in: query
          schema:
            type: string
            description: 必须提供的管理员名参数，用于查询管理员
          required: true
        - name: password
          in: query
          schema:
            type: string
            description: 可选，可设置管理员账号的新密码
          required: false
      security:
        - Authorization: [ ]
      responses:
        '200':
          description: 成功更新管理员信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
        '500':
          description: 密码加密失败或管理员更新错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: 信息
                  username:
                    type: string
                  error:
                    type: string
                    description: 错误信息

components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - Authorization: []